name: Deploy Hexo site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Hexo
        run: npm install hexo-cli -g

      - name: Install dependencies
        run: npm install

      - name: Install theme dependencies
        run: cd themes/pure && npm install && cd ../..

      - name: Generate static files
        run: hexo generate

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hexo deploy
