name: Deploy Hexo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install Hexo
        run: npm install hexo-cli -g

      - name: Install dependencies
        run: npm install

      - name: Install theme dependencies
        run: cd themes/landscape && npm install && cd ../..

      - name: Generate static files
        run: hexo generate

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: hexo deploy
